### ISSUE TITLE
Type 'ChatState' does not satisfy the constraint 'Action<any>'.

### ISSUE THREAD

**Issue by wildcart** [nprice1/typeScriptChatClient#1]
Hi,

I am trying to follow your project to set-up my own, as it is the most complete 'real life' example I found so far. However, updating the `[@types/][ract-]redux` dependencies causes the following error in `App.tsx` and `ChatApp.tsx`:
```
Type 'ChatState' does not satisfy the constraint 'Action<any>'.
  Property 'type' is missing in type 'ChatState'.
(alias) interface ChatState
import ChatState
```

This can be 'easily' fixed by the following:
```
- import { addUserAction } from '../actions';
+ import { Action, addUserAction } from '../actions';

- const mapDispatchToProps = (dispatch: redux.Dispatch<ChateState>): ConnectedDispatch => ({
+ const mapDispatchToProps = (dispatch: redux.Dispatch<Action>): ConnectedDispatch => ({
```

For me it seems much more logical the specify `Action` as type for `redux.Dispatch` as this is what's being dispatched after all. Maybe that's why it has been changed.

I briefly tested it and it seems to work, eg starting the client and server and opening the client in two browsers send messages between the browsers.

Excerpt of my `package.json`:
```
  "devDependencies" {
    "@types/react": "16.3.9",
    "@types/react-dom": "16.0.5",
    "@types/react-redux": "5.0.16",
  },
  "dependencies" {
    "react": "16.3.1",
    "react-dom": "16.3.1",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
  }
```

Btw: redux includes its own typings now and  `@types/redux` is no longer needed.

**Comment by nprice1** [comment]
Thanks for the clear fix for this, I just pushed a commit upping the versions of everything and using `Action` instead of `ChatState`.
